### ISSUE TITLE
エラーハンドリングでバグが発生

### ISSUE THREAD

**Issue by amotarao** [amotarao/yukukuru#5]
1日2回程度起きてる

```
TypeError: errors.find is not a function
    at Object.exports.checkRateLimitExceeded (/srv/lib/utils/firestore.js:9:26)
    at Object.exports.getFollowersList (/srv/lib/utils/twitter.js:40:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by amotarao** [comment]
```
{ errors: { Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }
```

```
{ errors: Error: JSON parseError with HTTP Status: 200 OK
    at Request._callback (/srv/node_modules/twitter/lib/twitter.js:166:25)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20) }
```

**Comment by amotarao** [comment]
twitter-client-v2 利用で無視していいレベルになった
